---
twitter: https://twitter.com/imShreyasPatil
github: https://github.com/PatilShreyas
linkedin: https://www.linkedin.com/in/patil-shreyas
youtube: ''
dribbble: ''
instagram: https://instagram.com/_patilshreyas/
facebook: https://www.facebook.com/shreyaspatil99
medium: https://medium.com/@patilshreyas
patreon: ''
paypal: ''
unsplash: ''
